services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /.docker-data/mp/core/mongo:/data/db
    networks:
      - service
  php:
    build:
      dockerfile: dev.Dockerfile
      context: ./.docker/php
    ports:
      - 8000:8000
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - core
      - service
networks:
  service:
    driver: bridge
  core:
    name: music-playground-core
    external: true