services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /.docker-data/mp/core/mongo:/data/db
    networks:
      - service
  core:
    build:
      dockerfile: dev.Dockerfile
      context: ./.docker/php
    ports:
      - 8000:8000
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - core
      - service
  core-s3:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    volumes:
      - /.docker-data/mp/core/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - PERSISTENCE=1
    networks:
      - core
      - s3
networks:
  service:
    driver: bridge
  core:
    name: music-playground-core
    external: true
  s3:
    name: music-playground-s3
    external: true