services:
  php:
    build:
      dockerfile: dev.Dockerfile
      context: ./.docker/php
    ports:
      - 8000:8000
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - core
networks:
  core:
    name: music-playground-core
    external: true