services:
  mongo:
    image: mongo
    restart: always
    profiles:
      - service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /.docker-data/mp/core/mongo:/data/db
    networks:
      - service
  core:
    build:
      dockerfile: dev.Dockerfile
      context: .docker/php
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - core
      - service
  core-s3:
    image: minio/minio:latest
    profiles:
      - service
    ports:
      - "4566:9000"
      - "9001:9001"
    volumes:
      - /.docker_data/mp/core/s3:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
    command: server /data --console-address ":9001"
    networks:
      - core
      - s3
  core-web:
    extends:
      service: core
    profiles:
      - service
    ports:
      - 8000:8000
    entrypoint: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
  core-worker-1:
    restart: always
    profiles:
      - workers
    extends:
      service: core
    command: >
      php bin/console messenger:consume amqp
      --queues=artists.update.1
      --queues=albums.update.1
      --queues=tracks.update.1
      --queues=playlists.create.1
      --bus=handle.bus -vv -f 10 --time-limit=300
  core-worker-2:
    restart: always
    profiles:
      - workers
    extends:
      service: core
    command: >
      php bin/console messenger:consume amqp
      --queues=artists.update.2
      --queues=albums.update.2
      --queues=tracks.update.2
      --queues=playlists.create.1
      --bus=handle.bus -vv -f 10 --time-limit=300
  core-worker-3:
    restart: always
    profiles:
      - workers
    extends:
      service: core
    command: >
      php bin/console messenger:consume amqp
      --queues=artists.update.3
      --queues=albums.update.3
      --queues=tracks.update.3
      --queues=playlists.create.1
      --bus=handle.bus -vv -f 10 --time-limit=300
  core-worker-4:
    restart: always
    profiles:
      - workers
    extends:
      service: core
    command: >
      php bin/console messenger:consume amqp
      --queues=artists.update.4
      --queues=albums.update.4
      --queues=tracks.update.4
      --queues=playlists.create.1
      --bus=handle.bus -vv -f 10 --time-limit=300
  core-playlist-worker:
    profiles:
      - workers
    extends:
      service: core
    command: >
      php bin/console messenger:consume amqp
      --queues=playlists.create.1
      --queues=playlists.create.2
      --queues=playlists.create.3
      --queues=playlists.create.4
      --bus=handle.bus -vv -f 10 --time-limit=300
networks:
  service:
    driver: bridge
  core:
    name: music-playground-core
    external: true
  s3:
    name: music-playground-s3
    external: true