parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #Messenger

    amqp_with_id_middleware:
        class: 'App\Shared\Infrastructure\Messenger\Middleware\AmqpWithIdMiddleware'
        arguments:
            $attributes:
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateArtistCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateAlbumCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
    exchange_stamp_middleware:
        class: 'MusicPlayground\AmqpTransport\Messenger\Middleware\AmqpExchangeStampMiddleware'
        arguments:
            $queues:
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateArtistCommand: 'artists.on_update'
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateAlbumCommand: 'albums.on_update'