parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    api.max_limit_value: 100

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #Messenger

    amqp_with_id_middleware:
        class: 'App\Shared\Infrastructure\Messenger\Middleware\AmqpWithIdMiddleware'
        arguments:
            $attributes:
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateArtistCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateAlbumCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateAlbumFullCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateTrackCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateArtistFullCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\SongParser\Command\ParsePlaylistCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\Playlist\Command\OnCreatedPlaylistCommand:
                    delivery_mode: 2
                    headers:
                        requeue: true
                MusicPlayground\Contract\Application\SongParser\Command\ParseTrackForPlaylistCommand:
                    delivery_mode: 2
    exchange_stamp_middleware:
        class: 'MusicPlayground\AmqpTransport\Messenger\Middleware\AmqpExchangeStampMiddleware'
        arguments:
            $queues:
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateArtistCommand: 'artists.on_update'
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateArtistFullCommand: 'artists.on_update_full'
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateAlbumCommand: 'albums.on_update'
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateAlbumFullCommand: 'albums.on_update_full'
                MusicPlayground\Contract\Application\SongParser\Command\OnUpdateTrackCommand: 'tracks.on_update'
                MusicPlayground\Contract\Application\SongParser\Command\ParsePlaylistCommand: 'playlists.parse'
                MusicPlayground\Contract\Application\Playlist\Command\OnCreatedPlaylistCommand: 'playlists.on_create'
                MusicPlayground\Contract\Application\Operation\OperationNotificationsCommand: 'operations'
                MusicPlayground\Contract\Application\SongParser\Command\ParseTrackForPlaylistCommand: 'tracks.parse'

    amqp_operation_middleware:
        alias: App\Shared\Infrastructure\Messenger\Middleware\AmqpOperationMiddleware
    #Core

    App\Core\Infrastructure\Controller\ArtistController:
        arguments:
            - '@App\Core\Domain\Repository\Artist\ArtistRepositoryInterface'
            - '%api.max_limit_value%'
    App\Core\Infrastructure\Controller\AlbumController:
        arguments:
            - '@App\Core\Domain\Repository\Album\AlbumRepositoryInterface'
            - '%api.max_limit_value%'
    App\Core\Infrastructure\Controller\TrackController:
        arguments:
            - '@App\Core\Domain\Repository\Track\TrackRepositoryInterface'
            - '%api.max_limit_value%'

    App\Core\Infrastructure\Normalizer\FileIdNormalizer:
        arguments:
            - '%env(FILE_SERVICE_HOST)%'

when@test:
    services:
        App\Tests\Core\Fixtures\AlbumFixture:
            - '@Doctrine\ODM\MongoDB\DocumentManager'
            - '@App\Shared\Domain\FlusherInterface'
        public.App\Core\Domain\Repository\ArtistRepositoryInterface:
            alias: App\Core\Domain\Repository\ArtistRepositoryInterface
            public: true
        public.App\Shared\Domain\FlusherInterface:
            alias: App\Shared\Domain\FlusherInterface
            public: true
        App\Tests\Core\Integration\Cleaner\CleanerInterface:
            class: App\Tests\Core\Integration\Cleaner\MongoCleaner
            public: true
            arguments:
                - '@Doctrine\ODM\MongoDB\DocumentManager'
        album-fixture:
            alias: App\Tests\Core\Fixtures\AlbumFixture
            public: fixture